---
stages:
  - lint

lint:
  stage: lint
  tags:
    - docker
  image: ${CI_REGISTRY}/hub/lint/ruby:2-6
  script:
    - apt-get update
    - apt-get --yes install libsqlite3-dev
    - bundle install --path vendor/bundle
    - bundle exec rubocop
